// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package secure_aggregation.willow;

import "willow/proto/shell/ciphertexts.proto";
import "willow/proto/willow/aggregation_config.proto";
import "willow/proto/zk/proofs.proto";

option java_multiple_files = true;
option java_outer_classname = "MessagesProto";


message ClientMessage {
  ShellKaheCiphertext kahe_ciphertext = 1;
  ShellAheCiphertext ahe_ciphertext = 2;
  RlweRelationProofListProto proof = 3;
  bytes nonce = 4;
}

message PartialDecryptionRequest {
  ShellAhePartialDecCiphertext partial_dec_ciphertext = 1;
  AggregationConfigProto aggregation_config = 2;
}

message PartialDecryptionResponse {
  ShellAhePartialDecryption partial_decryption = 1;
  // Noise contribution to the final aggregated result.
  CiphertextContribution dp_ciphertext_contribution = 2;
}

message CiphertextContribution {
  ShellKaheCiphertext kahe_ciphertext = 1;
  ShellAheRecoverCiphertext ahe_recover_ciphertext = 2;
}

message DecryptionRequestContribution {
  ShellAhePartialDecCiphertext partial_dec_ciphertext = 1;
  RlweRelationProofListProto proof = 2;
  bytes nonce = 3;
}

message DecryptorState {
  ShellAheSecretKeyShare sk_share = 1;
  AggregationConfigProto aggregation_config = 2;
}

message ServerState {
  map<string, ShellAhePublicKeyShare> decryptor_public_key_shares = 1;
  ShellKaheCiphertext client_sum_kahe = 2;
  ShellAheRecoverCiphertext client_sum_ahe_recover = 3;
  ShellAhePartialDecryption partial_decryption_sum = 4;
}

message VerifierState {
  ShellAhePartialDecCiphertext partial_dec_ciphertext_sum = 1;
  bytes nonce_lower_bound = 2;
  bytes nonce_upper_bound = 3;
}

// Result of finalizing an accumulator.
message FinalizedAccumulatorResult {
  // Serialized decryption request to include in a DecryptRequest to be sent to
  // the decryptor service.
  bytes decryption_request = 1;

  // Serialized state for creating a final result decryptor, which will handle
  // the response from the decryptor service and produce a plaintext aggregation
  // result.
  bytes final_result_decryptor_state = 2;
}

// An encrypted share of the PRNG state for secret sharing.
message SecretSharingContribution {
  bytes encrypted_share = 1;
}

// Public key independent half of ciphertext for DP noise.
message DPSetupContribution {
  // The public-key-independent half of the DP noise ciphertext (component_a).
  ShellAhePartialDecCiphertext dp_partial_dec_ciphertext = 1;
  // Proof of correct encryption, if applicable.
  RlweRelationProofListProto dp_partial_dec_ciphertext_proof = 2;
}

// A public key share and proof of knowledge of the secret key from a decryptor.
message KeyContribution {
  ShellAhePublicKeyShare public_key_share = 1;
  // Optional: absent if this is the only reputable decryptor.
  RlweRelationProofProto proof = 2;
}

// The initial contribution to the decryption key from a decryptor.
message SetupContribution {
  KeyContribution key_contribution = 1;
  // Only present if DP noise is being added.
  DPSetupContribution dp_setup = 2;
  // Encrypted randomness shares, only used by non-reputable decryptors.
  repeated SecretSharingContribution encrypted_randomness_shares = 3;
}

// A request to a surviving decryptor to decrypt shares of dropped decryptors.
message RecoveryRequest {
  repeated SecretSharingContribution encrypted_shares = 1;
}

// A response containing the decrypted shares of dropped decryptors.
message RecoveryResponse {
  repeated bytes decrypted_shares = 1;
}

// A request from the coordinator to reputable decryptors to verify key
// contributions.
message VerifyKeyContributionsRequest {
  repeated KeyContribution key_contributions = 1;
}
