// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package secure_aggregation.willow;

import "willow/proto/willow/aggregation_config.proto";
import "willow/proto/willow/messages.proto";

option java_multiple_files = true;
option java_outer_classname = "ServerAccumulatorProto";

message ServerAccumulatorState {
  ServerStateProto server_state = 1;
  AggregationConfigProto aggregation_config = 3;
  // We have one verifier state per range of nonces processed by this
  // accumulator. States get merged when adjacent ranges are processed.
  repeated VerifierStateProto verifier_states = 2;
  // The ranges of nonces processed by this accumulator. In the same order as
  // the corresponding verifier states.
  repeated NonceRange processed_nonce_ranges = 4;
}

message ClientMessageRange {
  repeated ClientMessage client_messages = 1;
  NonceRange nonce_range = 2;
}

// A range of nonces. Used to group client messages by nonce.
message NonceRange {
  bytes start = 1;  // Inclusive.
  bytes end = 2;    // Exclusive.
}

// State for creating a FinalResultDecryptor.
message FinalResultDecryptorState {
  ServerStateProto server_state = 1;
  AggregationConfigProto aggregation_config = 2;
}
